version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: freelance-db-simple
    environment:
      POSTGRES_DB: freelance_invoice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: